backend = "xrender";         # Use Xrender backend to reduce CPU load
corner-radius = 10;          # Adjust to your desired corner roundness

# Disable shadows, fading, and blur
shadow = false;
fading = false;
blur-method = "dual_kawase";

inactive-opacity = 0.999999999999;
active-opacity = 1.0;

# Optionally set vsync to reduce screen tearing
vsync = false;

